# What is Pandas?
## Pandas is a powerful library used for Data Manipulation and Analysis. It helps us to work with data in Tabular Format.

### Pandas provide functionalities and attributes to clean, organize and analyze large amounts of data.
### Pandas is built on top of NumPy, it introduces two key structures — Series and DataFrame — that make working with tabular and time-series data intuitive and fast.

### Pandas Vs Numpy:
#### NumPy: fast numerical computing on homogeneous arrays (all same dtype).
#### Pandas: labelled, heterogeneous tabular data (columns can have different dtypes) + built-in data cleaning tools.

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 2.3 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
     |████████████████████████████████| 347 kB 3.2 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/chinmai.muppa/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 4.9 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/chinmai.muppa/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.4
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd # 'pd' is the universal alias
import numpy as np
print(pd.__version__)

2.3.3

### Two Core Data Structures:
#### 1. Series -> 1D labelled array → A single column of a spreadsheet
#### 2. DataFrame -> 2D labelled table → A full spreadsheet with rows & columns

In [ ]:
# From list (default integer index)
s1 = pd.Series([10, 20, 30, 40, 50])

# From list with custom index
s2 = pd.Series([85, 92, 78], index=['Maths', 'Science', 'English'])

# From dictionary (keys become index)
s3 = pd.Series({'Mumbai': 20.7, 'Delhi': 31.1, 'Bangalore': 17.5})

# From scalar (broadcasts to all index positions)
s4 = pd.Series(5, index=['a', 'b', 'c', 'd'])

# From a NumPy Array with a custom index
data_array = np.array(['a', 'b', 'c', 'd'])
s_array = pd.Series(data_array, index=['w', 'x', 'y', 'z'])

print(s1)
print(s2)
print(s2['Maths']) # 85
# print(s2[0]) # 85 (positional also works) # Will be deprecated -> Use iloc[0]
print(s3)
print(s4)
print(s_array)

0    10
1    20
2    30
3    40
4    50
dtype: int64
Maths      85
Science    92
English    78
dtype: int64
85
Mumbai       20.7
Delhi        31.1
Bangalore    17.5
dtype: float64
a    5
b    5
c    5
d    5
dtype: int64
w    a
x    b
y    c
z    d
dtype: object

#### Series Attributes

In [9]:
s = pd.Series([10, 20, 30], index=['a','b','c'], name='scores')
print(s)
print(s.values) # [10 20 30]
print(s.index) # Index(['a', 'b', 'c'], dtype='object')
print(s.name) # scores
print(s.dtype)
print(s.shape)
print(s.size)

a    10
b    20
c    30
Name: scores, dtype: int64
[10 20 30]
Index(['a', 'b', 'c'], dtype='object')
scores
int64
(3,)
3

#### Accessing Elements

In [12]:
s = pd.Series([100, 200, 300, 400], index=['w','x','y','z'])
print(s['x']) # 200 — by label
print(s[1]) # 200 — by position # Use s.iloc[1]
print(s[['w','z']]) # multiple labels
print(s['x':'z']) # slicing by label (inclusive!)
print(s[1:3]) # slicing by position (exclusive end)

200
200
w    100
z    400
dtype: int64
x    200
y    300
z    400
dtype: int64
x    200
y    300
dtype: int64

/var/folders/hr/l8vxksbd5tzd3dcdp50328fw0000gp/T/ipykernel_49313/2332736125.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1]) # 200 — by position # Use s.iloc[1]

#### .to_numpy() or .values --> Converts the result into a clean NumPy array.

In [27]:
print(s[['w','z']].to_numpy())
print(s[['w','z']].values)
print(type(s[['w','z']].values))

[100 400]
[100 400]
<class 'numpy.ndarray'>

#### .tolist() --> Converts the result into a standard Python list.

In [26]:
print(s[['w','z']].to_list())
print(type(s[['w','z']].to_list()))

[100, 400]
<class 'list'>

### Mathematical Functions & Indexing in Series:

#### Arithmetic aligns on index labels automatically. Where labels don't match, the result is NaN (Not a Number).

In [31]:
s1 = pd.Series([1, 2, 3], index=['a','b','c'])
s2 = pd.Series([10, 20, 40], index=['a','b','d'])
print(s1 + s2)

a    11.0
b    22.0
c     NaN
d     NaN
dtype: float64

In [34]:
# fill_value replaces NaN during operation
# fill_value=0 parameter instructs Pandas to replace any missing or /
# NaN (Not a Number) values with 0 before performing the addition.
print(s1.add(s2, fill_value=0))

a    11.0
b    22.0
c     3.0
d    40.0
dtype: float64

#### Common Mathematical Methods

In [35]:
s = pd.Series([4, 7, 2, 9, 1, 5])
print(s.sum())
print(s.cumsum())
print(s.abs())
print(s.describe())

28
0     4
1    11
2    13
3    22
4    23
5    28
dtype: int64
0    4
1    7
2    2
3    9
4    1
5    5
dtype: int64
count    6.000000
mean     4.666667
std      3.011091
min      1.000000
25%      2.500000
50%      4.500000
75%      6.500000
max      9.000000
dtype: float64

### loc vs iloc
#### loc: Label-based → uses index labels; end is INCLUSIVE
#### iloc: Position-based → uses integer positions; end is EXCLUSIVE

In [36]:
s = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(s.loc['b':'d']) # b=20, c=30, d=40 (inclusive)
print(s.iloc[1:4]) # pos 1,2,3 → 20, 30, 40 (exclusive end)
print(s.loc[['a','c']]) # 10, 30 — multiple labels
print(s.iloc[[0,2,4]]) # 10, 30, 50 — multiple positions

b    20
c    30
d    40
dtype: int64
b    20
c    30
d    40
dtype: int64
a    10
c    30
dtype: int64
a    10
c    30
e    50
dtype: int64

### Real World Datasets in Series

#### DataFrame: Combination of multiple Series (Columns)
#### squeeze -> squeeze parameter makes sure that the data is in the Series format.

In [52]:
# read_csv() --> Reads content from the csv file in Pandas.
df = pd.read_csv('youtube_single_column2.csv')
df

                     Channel Name
0                 Smith-Ross Labs
1                Sandoval PLC Hub
2     Jones, Moore and Ho Network
3            Mitchell-Hooper Labs
4              Wilson LLC Studios
...                           ...
4995        Flores-Daniel Studios
4996     Spencer and Sons Studios
4997       Obrien-Roberts Studios
4998                 King Ltd Hub
4999            Henry Ltd Studios

[5000 rows x 1 columns]

In [56]:
type(df)

pandas.core.frame.DataFrame

In [58]:
# Read a single-column CSV as Series
s = pd.read_csv('youtube_single_column2.csv').squeeze('columns')
s

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: object

In [59]:
type(s)

pandas.core.series.Series

In [60]:
two_cols = pd.read_csv('youtube_two_column.csv')
two_cols

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [62]:
## index_col --> we can mention what specific column we want as an index column
pd.read_csv('youtube_two_column.csv', index_col='Youtuber Name').squeeze('columns')

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64